from dataclasses import dataclass
from typing import Any, Dict

@dataclass
class DocumentEmbeddingRequest:
    """ Defines properties for generating embeddings for a given document """

    # location of the document to index. Can be a file path, url or s3 url
    location:str

    # The content type of the document
    contentType:str

    # Name fo the table to insert embeddings into
    embeddingsTable:str='VectorIndex'

    # Additional colum values to insert into vector index table
    cols:Dict[str,Any]|None=None

    # If true embeddings for the document are generated by not inserted in to the embeddings table
    dryRun:bool=False
