#!/bin/bash
set -e
cd "$(dirname "$0")/.."


generate_env(){
    local ENV_PATH=$1
    echo '# Auto Generated by scripts/apply-config.sh' > $ENV_PATH
    echo '' >> $ENV_PATH
    echo '# CDK ouputs' >> $ENV_PATH
    scripts/get-cdk-output.sh >> $ENV_PATH
    echo "CDK ouputs > $(pwd)/$ENV_PATH"
}

copy_env(){
    local SRC=$1
    local ENV_PATH=$2
    cp $SRC $ENV_PATH
    echo "CDK ouputs > $(pwd)/$ENV_PATH"
}

generate_env '.env.test'
copy_env '.env.test' '.env.e2e'

